// Generated by the Manycore Form Compiler.
// https://github.com/gmarkall/manycore_form_compiler


#include "op_lib_cpp.h"
#include "op_seq_mat.h"
op_set elements;
op_dat Coordinate_data;
op_map Coordinate_map;
op_set Coordinate_set;
op_dat Tracer_data;
op_map Tracer_map;
op_set Tracer_set;

extern "C" void initialise_gpu_()
{
  op_init(0, 0, 2);
  elements = get_op_element_set();
  Tracer_data = get_op_dat("Tracer");
  Tracer_map = get_op_map("Tracer");
  Tracer_set = get_op_set("Tracer");
  Coordinate_data = get_op_dat("Coordinate");
  Coordinate_map = get_op_map("Coordinate");
  Coordinate_set = get_op_set("Coordinate");
}

extern "C" void finalise_gpu_()
{
  op_exit();
}

extern "C" void run_model_(double* dt_pointer)
{

}

extern "C" void return_fields_()
{

}


