// Generated by the Manycore Form Compiler.
// https://github.com/gmarkall/manycore_form_compiler


#include "cudastatic.hpp"
#include "cudastate.hpp"


__global__ void A(int n_ele, double* localTensor, double dt, double* c0)
{
  const double CG1_v[2][6][6] = { { {  0.0915762135097707,
                                     0.0915762135097707,
                                     0.8168475729804585,
                                     0.4459484909159649,
                                     0.4459484909159649,
                                     0.1081030181680702 },
                                   {  0.0915762135097707,
                                     0.8168475729804585,
                                     0.0915762135097707,
                                     0.4459484909159649,
                                     0.1081030181680702,
                                     0.4459484909159649 },
                                   {  0.8168475729804585,
                                     0.0915762135097707,
                                     0.0915762135097707,
                                     0.1081030181680702,
                                     0.4459484909159649,
                                     0.4459484909159649 },
                                   {  0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                , 0.                 },
                                   {  0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                , 0.                 },
                                   {  0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                , 0.                 } },

                                  { {  0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                , 0.                 },
                                   {  0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                , 0.                 },
                                   {  0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                , 0.                 },
                                   {  0.0915762135097707,
                                     0.0915762135097707,
                                     0.8168475729804585,
                                     0.4459484909159649,
                                     0.4459484909159649,
                                     0.1081030181680702 },
                                   {  0.0915762135097707,
                                     0.8168475729804585,
                                     0.0915762135097707,
                                     0.4459484909159649,
                                     0.1081030181680702,
                                     0.4459484909159649 },
                                   {  0.8168475729804585,
                                     0.0915762135097707,
                                     0.0915762135097707,
                                     0.1081030181680702,
                                     0.4459484909159649,
                                     0.4459484909159649 } } };
  const double d_CG1[3][6][2] = { { {  1., 0. },
                                   {  1., 0. },
                                   {  1., 0. },
                                   {  1., 0. },
                                   {  1., 0. },
                                   {  1., 0. } },

                                  { {  0., 1. },
                                   {  0., 1. },
                                   {  0., 1. },
                                   {  0., 1. },
                                   {  0., 1. },
                                   {  0., 1. } },

                                  { { -1.,-1. },
                                   { -1.,-1. },
                                   { -1.,-1. },
                                   { -1.,-1. },
                                   { -1.,-1. },
                                   { -1.,-1. } } };
  const double w[6] = {  0.0549758718276609, 0.0549758718276609,
                         0.0549758718276609, 0.1116907948390057,
                         0.1116907948390057, 0.1116907948390057 };
  double c_q0[6][2][2];
  for(int i_ele = THREAD_ID; i_ele < n_ele; i_ele += THREAD_COUNT)
  {
    for(int i_g = 0; i_g < 6; i_g++)
    {
      for(int i_d_0 = 0; i_d_0 < 2; i_d_0++)
      {
        for(int i_d_1 = 0; i_d_1 < 2; i_d_1++)
        {
          c_q0[i_g][i_d_0][i_d_1] = 0.0;
          for(int q_r_0 = 0; q_r_0 < 3; q_r_0++)
          {
            c_q0[i_g][i_d_0][i_d_1] += c0[i_ele + n_ele * (i_d_0 + 2 * q_r_0)] * d_CG1[q_r_0][i_g][i_d_1];
          };
        };
      };
    };
    for(int i_r_0 = 0; i_r_0 < 6; i_r_0++)
    {
      for(int i_r_1 = 0; i_r_1 < 6; i_r_1++)
      {
        localTensor[i_ele + n_ele * (i_r_0 + 6 * i_r_1)] = 0.0;
        for(int i_g = 0; i_g < 6; i_g++)
        {
          double ST1 = 0.0;
          double ST0 = 0.0;
          ST1 += c_q0[i_g][0][0] * c_q0[i_g][1][1] + -1 * c_q0[i_g][0][1] * c_q0[i_g][1][0];
          for(int i_d_0 = 0; i_d_0 < 2; i_d_0++)
          {
            ST0 += CG1_v[i_d_0][i_r_0][i_g] * CG1_v[i_d_0][i_r_1][i_g];
          };
          localTensor[i_ele + n_ele * (i_r_0 + 6 * i_r_1)] += ST0 * ST1 * w[i_g];
        };
      };
    };
  };
}

__global__ void RHS(int n_ele, double* localTensor, double dt, double* c0, double* c1)
{
  const double CG1[3][6] = { {  0.0915762135097707, 0.0915762135097707,
                               0.8168475729804585, 0.4459484909159649,
                               0.4459484909159649, 0.1081030181680702 },
                             {  0.0915762135097707, 0.8168475729804585,
                               0.0915762135097707, 0.4459484909159649,
                               0.1081030181680702, 0.4459484909159649 },
                             {  0.8168475729804585, 0.0915762135097707,
                               0.0915762135097707, 0.1081030181680702,
                               0.4459484909159649, 0.4459484909159649 } };
  const double CG1_v[2][6][6] = { { {  0.0915762135097707,
                                     0.0915762135097707,
                                     0.8168475729804585,
                                     0.4459484909159649,
                                     0.4459484909159649,
                                     0.1081030181680702 },
                                   {  0.0915762135097707,
                                     0.8168475729804585,
                                     0.0915762135097707,
                                     0.4459484909159649,
                                     0.1081030181680702,
                                     0.4459484909159649 },
                                   {  0.8168475729804585,
                                     0.0915762135097707,
                                     0.0915762135097707,
                                     0.1081030181680702,
                                     0.4459484909159649,
                                     0.4459484909159649 },
                                   {  0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                , 0.                 },
                                   {  0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                , 0.                 },
                                   {  0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                , 0.                 } },

                                  { {  0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                , 0.                 },
                                   {  0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                , 0.                 },
                                   {  0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                ,
                                     0.                , 0.                 },
                                   {  0.0915762135097707,
                                     0.0915762135097707,
                                     0.8168475729804585,
                                     0.4459484909159649,
                                     0.4459484909159649,
                                     0.1081030181680702 },
                                   {  0.0915762135097707,
                                     0.8168475729804585,
                                     0.0915762135097707,
                                     0.4459484909159649,
                                     0.1081030181680702,
                                     0.4459484909159649 },
                                   {  0.8168475729804585,
                                     0.0915762135097707,
                                     0.0915762135097707,
                                     0.1081030181680702,
                                     0.4459484909159649,
                                     0.4459484909159649 } } };
  const double d_CG1[3][6][2] = { { {  1., 0. },
                                   {  1., 0. },
                                   {  1., 0. },
                                   {  1., 0. },
                                   {  1., 0. },
                                   {  1., 0. } },

                                  { {  0., 1. },
                                   {  0., 1. },
                                   {  0., 1. },
                                   {  0., 1. },
                                   {  0., 1. },
                                   {  0., 1. } },

                                  { { -1.,-1. },
                                   { -1.,-1. },
                                   { -1.,-1. },
                                   { -1.,-1. },
                                   { -1.,-1. },
                                   { -1.,-1. } } };
  const double w[6] = {  0.0549758718276609, 0.0549758718276609,
                         0.0549758718276609, 0.1116907948390057,
                         0.1116907948390057, 0.1116907948390057 };
  double c_q1[6][2];
  double c_q0[6][2][2];
  for(int i_ele = THREAD_ID; i_ele < n_ele; i_ele += THREAD_COUNT)
  {
    for(int i_g = 0; i_g < 6; i_g++)
    {
      for(int i_d_0 = 0; i_d_0 < 2; i_d_0++)
      {
        c_q1[i_g][i_d_0] = 0.0;
        for(int q_r_0 = 0; q_r_0 < 3; q_r_0++)
        {
          c_q1[i_g][i_d_0] += c1[i_ele + n_ele * (i_d_0 + 2 * q_r_0)] * CG1[q_r_0][i_g];
        };
      };
      for(int i_d_0 = 0; i_d_0 < 2; i_d_0++)
      {
        for(int i_d_1 = 0; i_d_1 < 2; i_d_1++)
        {
          c_q0[i_g][i_d_0][i_d_1] = 0.0;
          for(int q_r_0 = 0; q_r_0 < 3; q_r_0++)
          {
            c_q0[i_g][i_d_0][i_d_1] += c0[i_ele + n_ele * (i_d_0 + 2 * q_r_0)] * d_CG1[q_r_0][i_g][i_d_1];
          };
        };
      };
    };
    for(int i_r_0 = 0; i_r_0 < 6; i_r_0++)
    {
      localTensor[i_ele + n_ele * i_r_0] = 0.0;
      for(int i_g = 0; i_g < 6; i_g++)
      {
        double ST3 = 0.0;
        double ST2 = 0.0;
        ST3 += c_q0[i_g][0][0] * c_q0[i_g][1][1] + -1 * c_q0[i_g][0][1] * c_q0[i_g][1][0];
        for(int i_d_0 = 0; i_d_0 < 2; i_d_0++)
        {
          ST2 += CG1_v[i_d_0][i_r_0][i_g] * c_q1[i_g][i_d_0];
        };
        localTensor[i_ele + n_ele * i_r_0] += ST2 * ST3 * w[i_g];
      };
    };
  };
}

StateHolder* state;
extern "C" void initialise_gpu_()
{
  state = new StateHolder();
  state->initialise();
  state->extractField("Velocity", 1);
  state->extractField("Coordinate", 1);
  state->allocateAllGPUMemory();
  state->transferAllFields();
}

extern "C" void finalise_gpu_()
{
  delete state;
}

extern "C" void run_model_(double* dt_pointer)
{
  double dt = *dt_pointer;
  int blockXDim = 64;
  int gridXDim = 128;
  double* localVector;
  double* localMatrix;
  double* globalVector;
  double* globalMatrix;
  double* solutionVector;
  CsrSparsity* Velocity_sparsity = state->getSparsity("Velocity");
  int* Velocity_colm = Velocity_sparsity->getCudaColm();
  int* Velocity_findrm = Velocity_sparsity->getCudaFindrm();
  int Velocity_colm_size = Velocity_sparsity->getSizeColm();
  int Velocity_findrm_size = Velocity_sparsity->getSizeFindrm();
  int Velocity_numEle = state->getNumEle("Velocity");
  int Velocity_numNodes = state->getNumNodes("Velocity");
  int* Velocity_eleNodes = state->getEleNodes("Velocity");
  int Velocity_nodesPerEle = state->getNodesPerEle("Velocity");
  int Velocity_numValsPerNode = state->getValsPerNode("Velocity");
  int Velocity_numVectorEntries = state->getNodesPerEle("Velocity");
  Velocity_numVectorEntries = Velocity_numVectorEntries * Velocity_numValsPerNode;
  cudaMalloc((void**)(&localMatrix), sizeof(double) * Velocity_numEle * Velocity_numVectorEntries * Velocity_numVectorEntries);
  double* CoordinateCoeff = state->getElementValue("Coordinate");
  A<<<gridXDim,blockXDim>>>(Velocity_numEle, localMatrix, dt, CoordinateCoeff);
  cudaMalloc((void**)(&globalMatrix), sizeof(double) * Velocity_colm_size);
  cudaMemset(globalMatrix, 0, sizeof(double) * Velocity_colm_size);
  matrix_addto<<<gridXDim,blockXDim>>>(Velocity_findrm, Velocity_colm, globalMatrix, Velocity_eleNodes, localMatrix, Velocity_numEle, Velocity_nodesPerEle);
  cudaFree(localMatrix);
  cudaMalloc((void**)(&localVector), sizeof(double) * Velocity_numEle * Velocity_numVectorEntries);
  double* VelocityCoeff = state->getElementValue("Velocity");
  RHS<<<gridXDim,blockXDim>>>(Velocity_numEle, localVector, dt, CoordinateCoeff, VelocityCoeff);
  cudaMalloc((void**)(&globalVector), sizeof(double) * Velocity_numNodes * Velocity_numValsPerNode);
  cudaMemset(globalVector, 0, sizeof(double) * Velocity_numValsPerNode * Velocity_numNodes);
  vector_addto<<<gridXDim,blockXDim>>>(globalVector, Velocity_eleNodes, localVector, Velocity_numEle, Velocity_nodesPerEle);
  cudaFree(localVector);
  cudaMalloc((void**)(&solutionVector), sizeof(double) * Velocity_numNodes * Velocity_numValsPerNode);
  cg_solve(Velocity_findrm, Velocity_findrm_size, Velocity_colm, Velocity_colm_size, globalMatrix, globalVector, Velocity_numNodes, solutionVector);
  cudaFree(globalMatrix);
  cudaFree(globalVector);
  expand_data<<<gridXDim,blockXDim>>>(VelocityCoeff, solutionVector, Velocity_eleNodes, Velocity_numEle, Velocity_numValsPerNode, Velocity_nodesPerEle);
  cudaFree(solutionVector);
}

extern "C" void return_fields_()
{
  state->returnFieldToHost("Velocity");
}



