# This file is part of the Manycore Form Compiler.
#
# The Manycore Form Compiler is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# 
# The Manycore Form Compiler is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
# 
# You should have received a copy of the GNU General Public License along with
# the Manycore Form Compiler.  If not, see <http://www.gnu.org/licenses>
#
# Copyright (c) 2011, Graham Markall <grm08@doc.ic.ac.uk> and others. Please see
# the AUTHORS file in the main source directory for a full list of copyright
# holders.


from ufl.form import Form
from codegeneration import ArbitraryString

class Driver:

    def drive(self, equation, fd):

        # Build Preamble
        preamble = self._buildPreamble()

        # Build forms
        # needs to happen first, since form_data attached to the forms is changed
        forms = [f for f in equation.uflObjects.values() if isinstance(f, Form)]
        for form in forms:
            assert form.form_data(), "Form has no form data attached!"
            form.form_data().code = self._formBackend.compile(form)

        # Build assembler
        definitions, declarations = self._assemblerBackend.compile(equation)

        #Unparse preamble
        print >>fd, preamble.unparse()

        # Unparse assembler defintions (headers)
        print >>fd, definitions.unparse()
        print >>fd

        # Unparse form kernel declarations
        for form in forms:
            print >>fd, form.form_data().code.unparse()
            print >>fd

        # Unparse assembler declarations (body)
        print >>fd, declarations.unparse()
        print >>fd

    def _buildPreamble(self):
        return ArbitraryString("// Generated by the Manycore Form Compiler.\n// https://github.com/gmarkall/manycore_form_compiler\n\n")

# vim:sw=4:ts=4:sts=4:et
